# Generated by Django 2.2.7 on 2020-08-28 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0017_auto_20200710_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('descripion1', models.TextField()),
                ('descripion2', models.TextField()),
                ('descripion3', models.TextField()),
                ('hire_period', models.SmallIntegerField()),
                ('new_scope', models.CharField(max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scope_end', models.TextField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Job')),
            ],
        ),
    ]
