# Generated by Django 2.2.7 on 2020-08-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='scope_end',
            field=models.TextField(blank=True, null=True),
        ),
    ]
