# Generated by Django 2.2.7 on 2020-08-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20200831_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='descripion1',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='descripion2',
            new_name='description2',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='descripion3',
            new_name='description3',
        ),
    ]
