# Generated by Django 2.2.7 on 2020-10-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_quote_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='invoice',
        ),
    ]
