# Generated by Django 2.2.7 on 2020-07-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200720_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='total_hours',
        ),
        migrations.AddField(
            model_name='employee',
            name='total_hours',
            field=models.DurationField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
