# Generated by Django 2.2.7 on 2020-06-17 02:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('size', models.CharField(max_length=50)),
                ('avail_quantity', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ordergear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_quantity', models.PositiveIntegerField()),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Gear')),
            ],
        ),
    ]
