# Generated by Django 2.2.7 on 2020-06-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200617_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='total',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='ordergear',
            old_name='subtotal',
            new_name='subtotal_price',
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
    ]
