# Generated by Django 2.2.7 on 2020-06-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200617_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gear',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gear',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
