# Generated by Django 2.2.7 on 2020-06-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200618_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
