# Generated by Django 2.2.7 on 2020-06-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200618_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='total_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
