# Generated by Django 2.2.7 on 2020-06-19 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200618_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returnedgear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.PositiveIntegerField()),
                ('fine_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remain_quantity', models.PositiveIntegerField()),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Gear')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='returned',
            field=models.ManyToManyField(to='main.Returnedgear'),
        ),
    ]
