# Generated by Django 2.2.7 on 2020-06-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200619_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('finished', 'finished')], default='active', max_length=50),
        ),
    ]
