# Generated by Django 2.2.7 on 2020-06-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='total_remain_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
