# Generated by Django 2.2.7 on 2020-06-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200626_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='size',
        ),
        migrations.AddField(
            model_name='gear',
            name='weight',
            field=models.DecimalField(decimal_places=4, max_digits=10),
            preserve_default=False,
        ),
    ]
