# Generated by Django 2.2.7 on 2020-06-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200630_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
