# Generated by Django 2.2.7 on 2020-06-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200630_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gear',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordergear',
            name='subtotal_price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnedgear',
            name='fine_price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
