# Generated by Django 2.2.7 on 2020-06-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200630_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='ordergear',
            name='subtotal_price',
        ),
        migrations.AddField(
            model_name='job',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordergear',
            name='subtotal_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
