# Generated by Django 2.2.7 on 2020-07-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200630_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
