# Generated by Django 2.2.7 on 2020-07-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_gear_total_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date',
            new_name='date_for_installation',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='site',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
