# Generated by Django 2.2.7 on 2020-06-30 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
        migrations.AddField(
            model_name='company',
            name='date_for_installation',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
