# Generated by Django 2.2.7 on 2020-07-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200630_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='builder_contact',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='builder_name',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='quote',
            field=models.FileField(blank=True, null=True, upload_to='quotes/'),
        ),
    ]
