# Generated by Django 2.2.7 on 2020-07-10 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200710_0600'),
        ('company', '0003_auto_20200710_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='builder_contact',
            new_name='amount_of_bays',
        ),
        migrations.RemoveField(
            model_name='company',
            name='date_for_installation',
        ),
        migrations.RemoveField(
            model_name='company',
            name='site',
        ),
        migrations.AddField(
            model_name='company',
            name='builder_abn',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='job_type',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='sub_contact',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='sub_name',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
