# Generated by Django 2.2.7 on 2020-08-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200712_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='amount_of_bays',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='company',
            name='builder_abn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='job_type',
            field=models.CharField(default='o', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='sub_contact',
            field=models.BigIntegerField(default='450405743'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sub_name',
            field=models.CharField(default='Sam', max_length=50),
        ),
    ]
