# Generated by Django 2.2.7 on 2020-09-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20200831_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='amount_of_bays',
        ),
        migrations.RemoveField(
            model_name='company',
            name='job',
        ),
        migrations.RemoveField(
            model_name='company',
            name='job_type',
        ),
    ]
