# Generated by Django 2.2.7 on 2020-09-08 13:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quote', '0003_auto_20200831_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description1', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('subtotal1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_dismantle', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quote.Quote')),
            ],
        ),
    ]
