# Generated by Django 2.2.7 on 2020-09-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20200909_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quantity1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity3',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
