# Generated by Django 2.2.7 on 2020-10-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20200911_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='quote',
        ),
    ]
