# Generated by Django 2.2.7 on 2020-10-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_remove_quote_invoice'),
        ('invoice', '0005_remove_invoice_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.Quote'),
            preserve_default=False,
        ),
    ]
