# Generated by Django 2.2.7 on 2020-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_remove_quote_invoice'),
        ('invoice', '0006_invoice_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='quote',
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.ManyToManyField(to='quote.Quote'),
        ),
    ]
