# Generated by Django 2.2.7 on 2020-10-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20201007_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='abn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
