# Generated by Django 2.2.7 on 2020-10-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_remove_quote_invoice'),
        ('invoice', '0008_auto_20201007_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='quote',
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quote.Quote'),
            preserve_default=False,
        ),
    ]
